# Generated by Django 3.0 on 2022-03-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skintonedetectionimage',
            name='navigation_instruction',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='skintonedetectionimage',
            name='primary_light_direction',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='skintonedetectionimage',
            name='scene_brightness_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='skintonedetectionimage',
            name='scene_brightness_value',
            field=models.IntegerField(null=True),
        ),
    ]
