# Generated by Django 3.0 on 2022-03-19 02:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20220317_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinTone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('rgb_values', models.CharField(blank=True, max_length=200)),
                ('color_profile', models.CharField(blank=True, max_length=200)),
                ('percentage_of_face_mask', models.IntegerField()),
                ('skin_tone_detection_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.SkinToneDetectionImage')),
            ],
        ),
    ]
