# Generated by Django 3.0 on 2022-04-28 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_skintone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalkingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_teeth_visible', models.BooleanField(null=True)),
                ('scene_brightness_value', models.IntegerField(null=True)),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.UserSession')),
            ],
        ),
        migrations.CreateModel(
            name='RotationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('heading', models.IntegerField(null=True)),
                ('relative_image_path', models.CharField(blank=True, max_length=200)),
                ('primary_light_direction', models.CharField(blank=True, max_length=200)),
                ('average_face_brightness_value', models.IntegerField(null=True)),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.UserSession')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('rgb_values', models.CharField(blank=True, max_length=200)),
                ('profile', models.CharField(blank=True, max_length=200)),
                ('percentage_of_face_mask', models.IntegerField()),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.UserSession')),
            ],
        ),
    ]
